<a href="https://colab.research.google.com/github/KULDEEPSONI-source/DEEPLEARNING/blob/main/keras_hyperparameter_tunning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [222]:
import numpy as np
import pandas as pd

In [223]:
df = pd.read_csv('diabetes.csv')

In [224]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [225]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

X = df.iloc[:, :-1]   # all columns except last → features
y = df.iloc[:, -1]    # only the last column → target/label

In [226]:
x=df.iloc[:,:8].values
y=df.iloc[:,8].values

In [227]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X= scaler.fit_transform(x)
#

In [228]:
X.shape

(768, 8)

In [229]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [230]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [231]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer = 'Adam', loss= 'binary_crossentropy' , metrics=['accuracy'])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [232]:
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.6645 - loss: 0.6555 - val_accuracy: 0.6429 - val_loss: 0.6336
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6726 - loss: 0.5981 - val_accuracy: 0.6753 - val_loss: 0.5814
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6922 - loss: 0.5528 - val_accuracy: 0.7078 - val_loss: 0.5433
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5210 - val_accuracy: 0.7403 - val_loss: 0.5172
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4998 - val_accuracy: 0.7468 - val_loss: 0.4984
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7720 - loss: 0.4838 - val_accuracy: 0.7662 - val_loss: 0.4857
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4720 - val_accuracy: 0.7727 - val_loss: 0.4784
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4643 - val_accuracy: 0.7857 - val_loss: 0.4738
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4578 - val_accuracy: 0.7857 - val_loss: 0.4702
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4525 - val_accuracy: 0.7922 - val_loss: 0.4674
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4499 - val_accuracy: 0.7857 - val_loss: 0.4691
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.4470 - val_accuracy: 0.7987 - val_loss: 0.4685
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7736 - loss: 0.4449 - val_accuracy: 0.7922 - val_loss: 0.4676
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4423 - val_accuracy: 0.8052 - val_loss: 0.4668
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7769 - loss: 0.4415 - val_accuracy: 0.7922 - val_loss: 0.4682
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7801 - loss: 0.4381 - val_accuracy: 0.7922 - val_loss: 0.4673
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4372 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4352 - val_accuracy: 0.7922 - val_loss: 0.4672
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4339 - val_accuracy: 0.7922 - val_loss: 0.4672
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4319 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7866 - loss: 0.4312 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4296 - val_accuracy: 0.7922 - val_loss: 0.4663
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4290 - val_accuracy: 0.7987 - val_loss: 0.4654
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4270 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4264 - val_accuracy: 0.7922 - val_loss: 0.4684
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4251 - val_accuracy: 0.7857 - val_loss: 0.4662
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4241 - val_accuracy: 0.7857 - val_loss: 0.4668
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4229 - val_accuracy: 0.7857 - val_loss: 0.4653
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4220 - val_accuracy: 0.7857 - val_loss: 0.4670
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4210 - val_accuracy: 0.7987 - val_loss: 0.4661
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4197 - val_accuracy: 0.7857 - val_loss: 0.4674
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4185 - val_accuracy: 0.7857 - val_loss: 0.4681
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4172 - val_accuracy: 0.7857 - val_loss: 0.4660
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4172 - val_accuracy: 0.7922 - val_loss: 0.4667
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4151 - val_accuracy: 0.8117 - val_loss: 0.4651
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4140 - val_accuracy: 0.7987 - val_loss: 0.4652
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4128 - val_accuracy: 0.7922 - val_loss: 0.4641
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4121 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4116 - val_accuracy: 0.7987 - val_loss: 0.4641
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4101 - val_accuracy: 0.8052 - val_loss: 0.4652
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4091 - val_accuracy: 0.8052 - val_loss: 0.4658
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4073 - val_accuracy: 0.8117 - val_loss: 0.4672
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4063 - val_accuracy: 0.8247 - val_loss: 0.4673
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4048 - val_accuracy: 0.8182 - val_loss: 0.4669
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4038 - val_accuracy: 0.8182 - val_loss: 0.4673
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4031 - val_accuracy: 0.8182 - val_loss: 0.4686
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4027 - val_accuracy: 0.8182 - val_loss: 0.4670
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4006 - val_accuracy: 0.8182 - val_loss: 0.4669
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3995 - val_accuracy: 0.8182 - val_loss: 0.4686
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3986 - val_accuracy: 0.8182 - val_loss: 0.4708
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3972 - val_accuracy: 0.8117 - val_loss: 0.4716
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3963 - val_accuracy: 0.8182 - val_loss: 0.4695
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3965 - val_accuracy: 0.8117 - val_loss: 0.4702
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3948 - val_accuracy: 0.8117 - val_loss: 0.4741
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3954 - val_accuracy: 0.8117 - val_loss: 0.4732
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8160 - loss: 0.3925 - val_accuracy: 0.8182 - val_loss: 0.4723
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3935 - val_accuracy: 0.8182 - val_loss: 0.4732
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.3907 - val_accuracy: 0.8182 - val_loss: 0.4703
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8160 - loss: 0.3896 - val_accuracy: 0.8182 - val_loss: 0.4718
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3880 - val_accuracy: 0.8247 - val_loss: 0.4732
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3875 - val_accuracy: 0.8312 - val_loss: 0.4716
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.3881 - val_accuracy: 0.8117 - val_loss: 0.4736
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3864 - val_accuracy: 0.8312 - val_loss: 0.4746
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3844 - val_accuracy: 0.8182 - val_loss: 0.4755
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3844 - val_accuracy: 0.8117 - val_loss: 0.4744
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.3834 - val_accuracy: 0.8117 - val_loss: 0.4727
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3836 - val_accuracy: 0.8312 - val_loss: 0.4746
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3809 - val_accuracy: 0.8312 - val_loss: 0.4771
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3791 - val_accuracy: 0.8312 - val_loss: 0.4758
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3783 - val_accuracy: 0.8247 - val_loss: 0.4789
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3774 - val_accuracy: 0.8182 - val_loss: 0.4782
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3769 - val_accuracy: 0.8247 - val_loss: 0.4791
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3770 - val_accuracy: 0.8182 - val_loss: 0.4754
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3753 - val_accuracy: 0.8247 - val_loss: 0.4791
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3758 - val_accuracy: 0.8247 - val_loss: 0.4730
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3728 - val_accuracy: 0.8312 - val_loss: 0.4772
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3705 - val_accuracy: 0.8182 - val_loss: 0.4767
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8339 - loss: 0.3701 - val_accuracy: 0.8182 - val_loss: 0.4768
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3708 - val_accuracy: 0.8182 - val_loss: 0.4801
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3673 - val_accuracy: 0.8182 - val_loss: 0.4795
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3672 - val_accuracy: 0.8247 - val_loss: 0.4812
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3660 - val_accuracy: 0.8247 - val_loss: 0.4787
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3641 - val_accuracy: 0.8117 - val_loss: 0.4798
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3649 - val_accuracy: 0.8247 - val_loss: 0.4782
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3645 - val_accuracy: 0.8117 - val_loss: 0.4829
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3616 - val_accuracy: 0.8052 - val_loss: 0.4862
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3611 - val_accuracy: 0.8052 - val_loss: 0.4832
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3608 - val_accuracy: 0.8052 - val_loss: 0.4843
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3589 - val_accuracy: 0.8117 - val_loss: 0.4846
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3582 - val_accuracy: 0.8117 - val_loss: 0.4845
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3594 - val_accuracy: 0.8052 - val_loss: 0.4841
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8436 - loss: 0.3565 - val_accuracy: 0.8117 - val_loss: 0.4878
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8420 - loss: 0.3561 - val_accuracy: 0.8052 - val_loss: 0.4911
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8436 - loss: 0.3568 - val_accuracy: 0.8052 - val_loss: 0.4900
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8436 - loss: 0.3531 - val_accuracy: 0.8117 - val_loss: 0.4855
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8502 - loss: 0.3541 - val_accuracy: 0.8052 - val_loss: 0.4875
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8502 - loss: 0.3511 - val_accuracy: 0.8052 - val_loss: 0.4911
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8485 - loss: 0.3508 - val_accuracy: 0.7987 - val_loss: 0.4878
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8436 - loss: 0.3499 - val_accuracy: 0.7987 - val_loss: 0.4879
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8469 - loss: 0.3493 - val_accuracy: 0.8052 - val_loss: 0.4886

In [233]:
# 1.how to select appropriate optimizer
# 2. NO, of nodes in a layer
# 3. how to select no. of hidden layer

In [234]:
# !pip install keras-tuner

In [235]:
import kerastuner as kt

In [236]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop','adadelta'])
  model.compile(optimizer = optimizer, loss= 'binary_crossentropy' , metrics=['accuracy'])
  return model

In [237]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [238]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [239]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [240]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [241]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [242]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7492 - loss: 0.5291 - val_accuracy: 0.7987 - val_loss: 0.5092
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5153 - val_accuracy: 0.7792 - val_loss: 0.4992
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5048 - val_accuracy: 0.7922 - val_loss: 0.4926
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4968 - val_accuracy: 0.7857 - val_loss: 0.4857
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4897 - val_accuracy: 0.7792 - val_loss: 0.4801
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4836 - val_accuracy: 0.7857 - val_loss: 0.4760
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4785 - val_accuracy: 0.7792 - val_loss: 0.4721
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4750 - val_accuracy: 0.7922 - val_loss: 0.4701
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4713 - val_accuracy: 0.7857 - val_loss: 0.4674
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4683 - val_accuracy: 0.7922 - val_loss: 0.4666
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4658 - val_accuracy: 0.7987 - val_loss: 0.4652
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4642 - val_accuracy: 0.7987 - val_loss: 0.4663
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4621 - val_accuracy: 0.7987 - val_loss: 0.4656
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4610 - val_accuracy: 0.8117 - val_loss: 0.4644
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4593 - val_accuracy: 0.8052 - val_loss: 0.4640
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4584 - val_accuracy: 0.8117 - val_loss: 0.4633
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4569 - val_accuracy: 0.7922 - val_loss: 0.4630
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4559 - val_accuracy: 0.7857 - val_loss: 0.4635
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4549 - val_accuracy: 0.7922 - val_loss: 0.4621
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4536 - val_accuracy: 0.7922 - val_loss: 0.4619
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4530 - val_accuracy: 0.8052 - val_loss: 0.4609
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4525 - val_accuracy: 0.8052 - val_loss: 0.4608
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4523 - val_accuracy: 0.8052 - val_loss: 0.4628
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4509 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4506 - val_accuracy: 0.7987 - val_loss: 0.4619
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4497 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4489 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4480 - val_accuracy: 0.8052 - val_loss: 0.4600
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4476 - val_accuracy: 0.7987 - val_loss: 0.4609
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4468 - val_accuracy: 0.7987 - val_loss: 0.4608
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4467 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4457 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4458 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4448 - val_accuracy: 0.7987 - val_loss: 0.4607
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4441 - val_accuracy: 0.8052 - val_loss: 0.4595
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4439 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4434 - val_accuracy: 0.8052 - val_loss: 0.4596
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4433 - val_accuracy: 0.7922 - val_loss: 0.4596
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4427 - val_accuracy: 0.7922 - val_loss: 0.4607
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4424 - val_accuracy: 0.7922 - val_loss: 0.4604
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4418 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4412 - val_accuracy: 0.7922 - val_loss: 0.4603
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4404 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4401 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4396 - val_accuracy: 0.7922 - val_loss: 0.4605
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4395 - val_accuracy: 0.7922 - val_loss: 0.4608
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4390 - val_accuracy: 0.7922 - val_loss: 0.4606
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4385 - val_accuracy: 0.7857 - val_loss: 0.4607
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4381 - val_accuracy: 0.7857 - val_loss: 0.4586
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4375 - val_accuracy: 0.7857 - val_loss: 0.4589
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4373 - val_accuracy: 0.7922 - val_loss: 0.4586
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4366 - val_accuracy: 0.7857 - val_loss: 0.4588
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4362 - val_accuracy: 0.7857 - val_loss: 0.4595
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4362 - val_accuracy: 0.7922 - val_loss: 0.4597
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4362 - val_accuracy: 0.7857 - val_loss: 0.4594
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4351 - val_accuracy: 0.7922 - val_loss: 0.4584
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4347 - val_accuracy: 0.7922 - val_loss: 0.4575
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4360 - val_accuracy: 0.7987 - val_loss: 0.4567
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4356 - val_accuracy: 0.7922 - val_loss: 0.4569
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4337 - val_accuracy: 0.7922 - val_loss: 0.4575
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4334 - val_accuracy: 0.7987 - val_loss: 0.4577
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4327 - val_accuracy: 0.7987 - val_loss: 0.4572
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4325 - val_accuracy: 0.7922 - val_loss: 0.4567
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4321 - val_accuracy: 0.7987 - val_loss: 0.4567
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4318 - val_accuracy: 0.8117 - val_loss: 0.4582
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4319 - val_accuracy: 0.8052 - val_loss: 0.4583
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7866 - loss: 0.4313 - val_accuracy: 0.7987 - val_loss: 0.4582
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4307 - val_accuracy: 0.7987 - val_loss: 0.4570
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7883 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4570
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4312 - val_accuracy: 0.7922 - val_loss: 0.4579
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4297 - val_accuracy: 0.7987 - val_loss: 0.4566
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4296 - val_accuracy: 0.8117 - val_loss: 0.4553
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4293 - val_accuracy: 0.8117 - val_loss: 0.4555
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4285 - val_accuracy: 0.8247 - val_loss: 0.4561
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4300 - val_accuracy: 0.8182 - val_loss: 0.4550
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4284 - val_accuracy: 0.8182 - val_loss: 0.4559
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4280 - val_accuracy: 0.7987 - val_loss: 0.4569
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4274 - val_accuracy: 0.8182 - val_loss: 0.4564
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4273 - val_accuracy: 0.8247 - val_loss: 0.4555
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4265 - val_accuracy: 0.8182 - val_loss: 0.4568
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4267 - val_accuracy: 0.8182 - val_loss: 0.4566
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4265 - val_accuracy: 0.8117 - val_loss: 0.4572
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4260 - val_accuracy: 0.8247 - val_loss: 0.4556
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4257 - val_accuracy: 0.8247 - val_loss: 0.4556
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4250 - val_accuracy: 0.8182 - val_loss: 0.4566
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4248 - val_accuracy: 0.8117 - val_loss: 0.4571
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4248 - val_accuracy: 0.8182 - val_loss: 0.4555
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4246 - val_accuracy: 0.8182 - val_loss: 0.4564
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4242 - val_accuracy: 0.8247 - val_loss: 0.4567
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4238 - val_accuracy: 0.8247 - val_loss: 0.4567
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4235 - val_accuracy: 0.8247 - val_loss: 0.4571
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4241 - val_accuracy: 0.8247 - val_loss: 0.4570
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4229 - val_accuracy: 0.8182 - val_loss: 0.4562
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.8182 - val_loss: 0.4569

# 2. NO, of nodes in a layer

In [243]:
def build_model(hp):
  model = Sequential()
  units = hp.Int('units', min_value=8, max_value=64, step=8)
  model.add(Dense(units, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  optimizer = hp.Choice('optimizer', values=['adam', 'sgd', 'rmsprop','adadelta'])
  model.compile(optimizer = optimizer, loss= 'binary_crossentropy' , metrics=['accuracy'])
  return model
#

In [244]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory = ' mydir')

Reloading Tuner from  mydir/untitled_project/tuner0.json

In [245]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [246]:
tuner.get_best_hyperparameters()[0].values

{'units': 48, 'optimizer': 'adam'}

In [247]:
model = tuner.get_best_models(num_models=1)[0]

In [248]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.7655 - loss: 0.5266 - val_accuracy: 0.7987 - val_loss: 0.4986
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.5047 - val_accuracy: 0.7987 - val_loss: 0.4818
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4912 - val_accuracy: 0.7857 - val_loss: 0.4708
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4798 - val_accuracy: 0.7792 - val_loss: 0.4647
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4729 - val_accuracy: 0.7792 - val_loss: 0.4599
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4678 - val_accuracy: 0.7857 - val_loss: 0.4567
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4629 - val_accuracy: 0.7987 - val_loss: 0.4539
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4591 - val_accuracy: 0.7987 - val_loss: 0.4520
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4558 - val_accuracy: 0.7922 - val_loss: 0.4514
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4534 - val_accuracy: 0.7857 - val_loss: 0.4513
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4511 - val_accuracy: 0.7922 - val_loss: 0.4506
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4497 - val_accuracy: 0.7922 - val_loss: 0.4513
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4476 - val_accuracy: 0.7857 - val_loss: 0.4517
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4462 - val_accuracy: 0.7922 - val_loss: 0.4505
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4450 - val_accuracy: 0.7857 - val_loss: 0.4492
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4437 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4424 - val_accuracy: 0.7987 - val_loss: 0.4518
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4413 - val_accuracy: 0.7987 - val_loss: 0.4514
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4401 - val_accuracy: 0.8052 - val_loss: 0.4493
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4392 - val_accuracy: 0.8052 - val_loss: 0.4501
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4385 - val_accuracy: 0.8117 - val_loss: 0.4503
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4376 - val_accuracy: 0.8117 - val_loss: 0.4501
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4366 - val_accuracy: 0.8117 - val_loss: 0.4490
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4357 - val_accuracy: 0.7987 - val_loss: 0.4494
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4351 - val_accuracy: 0.7987 - val_loss: 0.4503
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4343 - val_accuracy: 0.8117 - val_loss: 0.4502
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4339 - val_accuracy: 0.7922 - val_loss: 0.4508
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4332 - val_accuracy: 0.8182 - val_loss: 0.4498
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7866 - loss: 0.4323 - val_accuracy: 0.7857 - val_loss: 0.4505
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4312 - val_accuracy: 0.7857 - val_loss: 0.4516
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7883 - loss: 0.4314 - val_accuracy: 0.7857 - val_loss: 0.4527
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7899 - loss: 0.4305 - val_accuracy: 0.7987 - val_loss: 0.4510
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4300 - val_accuracy: 0.7987 - val_loss: 0.4511
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4287 - val_accuracy: 0.7987 - val_loss: 0.4514
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4280 - val_accuracy: 0.8052 - val_loss: 0.4514
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4276 - val_accuracy: 0.8052 - val_loss: 0.4495
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4271 - val_accuracy: 0.8052 - val_loss: 0.4504
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4265 - val_accuracy: 0.7987 - val_loss: 0.4501
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4256 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4253 - val_accuracy: 0.8117 - val_loss: 0.4509
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4254 - val_accuracy: 0.7987 - val_loss: 0.4482
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4244 - val_accuracy: 0.7987 - val_loss: 0.4485
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4241 - val_accuracy: 0.7987 - val_loss: 0.4476
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4233 - val_accuracy: 0.7987 - val_loss: 0.4463
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4223 - val_accuracy: 0.7987 - val_loss: 0.4480
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4222 - val_accuracy: 0.8052 - val_loss: 0.4481
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4218 - val_accuracy: 0.8117 - val_loss: 0.4494
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4213 - val_accuracy: 0.7987 - val_loss: 0.4509
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4205 - val_accuracy: 0.7922 - val_loss: 0.4514
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4198 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4203 - val_accuracy: 0.8052 - val_loss: 0.4510
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4192 - val_accuracy: 0.7922 - val_loss: 0.4517
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4184 - val_accuracy: 0.7987 - val_loss: 0.4517
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4178 - val_accuracy: 0.7987 - val_loss: 0.4508
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4178 - val_accuracy: 0.8052 - val_loss: 0.4511
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4163 - val_accuracy: 0.7987 - val_loss: 0.4533
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4167 - val_accuracy: 0.7922 - val_loss: 0.4527
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4165 - val_accuracy: 0.7922 - val_loss: 0.4531
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8078 - loss: 0.4150 - val_accuracy: 0.7987 - val_loss: 0.4536
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8094 - loss: 0.4149 - val_accuracy: 0.7922 - val_loss: 0.4509
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4143 - val_accuracy: 0.8052 - val_loss: 0.4503
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4133 - val_accuracy: 0.7987 - val_loss: 0.4511
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4130 - val_accuracy: 0.7987 - val_loss: 0.4518
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4126 - val_accuracy: 0.7922 - val_loss: 0.4502
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.4115 - val_accuracy: 0.7987 - val_loss: 0.4505
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.4119 - val_accuracy: 0.8052 - val_loss: 0.4498
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8127 - loss: 0.4113 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4110 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4103 - val_accuracy: 0.8052 - val_loss: 0.4492
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4098 - val_accuracy: 0.8052 - val_loss: 0.4501
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4099 - val_accuracy: 0.8052 - val_loss: 0.4499
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.4092 - val_accuracy: 0.8052 - val_loss: 0.4499
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8208 - loss: 0.4084 - val_accuracy: 0.8052 - val_loss: 0.4506
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4080 - val_accuracy: 0.7987 - val_loss: 0.4526
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8225 - loss: 0.4074 - val_accuracy: 0.8052 - val_loss: 0.4513
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.4071 - val_accuracy: 0.8052 - val_loss: 0.4525
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.4070 - val_accuracy: 0.8052 - val_loss: 0.4534
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.4064 - val_accuracy: 0.8052 - val_loss: 0.4509
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.4056 - val_accuracy: 0.8052 - val_loss: 0.4502
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.4059 - val_accuracy: 0.7987 - val_loss: 0.4513
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.4053 - val_accuracy: 0.8052 - val_loss: 0.4505
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4046 - val_accuracy: 0.8052 - val_loss: 0.4509
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4042 - val_accuracy: 0.8052 - val_loss: 0.4534
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.4031 - val_accuracy: 0.8052 - val_loss: 0.4519
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4034 - val_accuracy: 0.8052 - val_loss: 0.4524
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.4026 - val_accuracy: 0.8052 - val_loss: 0.4522
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.4032 - val_accuracy: 0.8052 - val_loss: 0.4545
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.4023 - val_accuracy: 0.8052 - val_loss: 0.4519
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.4018 - val_accuracy: 0.8117 - val_loss: 0.4510
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.4016 - val_accuracy: 0.7987 - val_loss: 0.4532
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.4006 - val_accuracy: 0.8052 - val_loss: 0.4530
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.4006 - val_accuracy: 0.8052 - val_loss: 0.4528
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.4004 - val_accuracy: 0.8052 - val_loss: 0.4542
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.4005 - val_accuracy: 0.8052 - val_loss: 0.4542

# 3. how to select no. of hidden layer

In [249]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(72, activation='relu', input_dim=8))
  for i in range(hp.Int('num_layers', min_value=1, max_value=10)):
    model.add(Dense(72, activation='relu'))
  model.add(Dense(1,activation='sigmoid'))

  model.compile(optimizer='adam',
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

In [250]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=3,directory = 'my_dt')

Reloading Tuner from my_dt/untitled_project/tuner0.json

In [251]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [252]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 7}

In [253]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8274 - loss: 0.3995 - val_accuracy: 0.8052 - val_loss: 0.4540
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3990 - val_accuracy: 0.8117 - val_loss: 0.4529
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8257 - loss: 0.3994 - val_accuracy: 0.8117 - val_loss: 0.4532
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.4004 - val_accuracy: 0.8182 - val_loss: 0.4557
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3983 - val_accuracy: 0.8117 - val_loss: 0.4557
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3980 - val_accuracy: 0.8117 - val_loss: 0.4548
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3982 - val_accuracy: 0.8052 - val_loss: 0.4581
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3973 - val_accuracy: 0.8052 - val_loss: 0.4573
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3970 - val_accuracy: 0.8117 - val_loss: 0.4556
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3962 - val_accuracy: 0.7987 - val_loss: 0.4584
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3955 - val_accuracy: 0.8052 - val_loss: 0.4573
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8322 - loss: 0.3965 - val_accuracy: 0.8117 - val_loss: 0.4572
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8339 - loss: 0.3953 - val_accuracy: 0.8052 - val_loss: 0.4574
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8371 - loss: 0.3950 - val_accuracy: 0.8052 - val_loss: 0.4587
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8355 - loss: 0.3948 - val_accuracy: 0.8052 - val_loss: 0.4589
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8339 - loss: 0.3949 - val_accuracy: 0.8117 - val_loss: 0.4595
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8290 - loss: 0.3953 - val_accuracy: 0.8117 - val_loss: 0.4588
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8274 - loss: 0.3933 - val_accuracy: 0.8117 - val_loss: 0.4587
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8322 - loss: 0.3939 - val_accuracy: 0.8117 - val_loss: 0.4575
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8306 - loss: 0.3937 - val_accuracy: 0.8117 - val_loss: 0.4584
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8339 - loss: 0.3929 - val_accuracy: 0.8117 - val_loss: 0.4578
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8388 - loss: 0.3919 - val_accuracy: 0.7987 - val_loss: 0.4596
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3921 - val_accuracy: 0.8117 - val_loss: 0.4605
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3913 - val_accuracy: 0.8117 - val_loss: 0.4595
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3909 - val_accuracy: 0.8117 - val_loss: 0.4590
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3907 - val_accuracy: 0.8117 - val_loss: 0.4577
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8388 - loss: 0.3908 - val_accuracy: 0.8117 - val_loss: 0.4591
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3898 - val_accuracy: 0.8052 - val_loss: 0.4593
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3909 - val_accuracy: 0.8117 - val_loss: 0.4613
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3894 - val_accuracy: 0.8052 - val_loss: 0.4591
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3902 - val_accuracy: 0.8052 - val_loss: 0.4598
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3884 - val_accuracy: 0.8117 - val_loss: 0.4579
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3884 - val_accuracy: 0.8117 - val_loss: 0.4604
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3892 - val_accuracy: 0.8117 - val_loss: 0.4631
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3881 - val_accuracy: 0.8117 - val_loss: 0.4611
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3872 - val_accuracy: 0.8052 - val_loss: 0.4605
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3874 - val_accuracy: 0.8052 - val_loss: 0.4588
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3876 - val_accuracy: 0.8117 - val_loss: 0.4602
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3865 - val_accuracy: 0.8052 - val_loss: 0.4587
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3863 - val_accuracy: 0.8052 - val_loss: 0.4573
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3861 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3871 - val_accuracy: 0.8052 - val_loss: 0.4605
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8241 - loss: 0.3872 - val_accuracy: 0.8117 - val_loss: 0.4603
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3854 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3844 - val_accuracy: 0.8052 - val_loss: 0.4613
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3849 - val_accuracy: 0.8052 - val_loss: 0.4600
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3833 - val_accuracy: 0.8052 - val_loss: 0.4596
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3845 - val_accuracy: 0.8117 - val_loss: 0.4611
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3838 - val_accuracy: 0.8182 - val_loss: 0.4611
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3834 - val_accuracy: 0.8182 - val_loss: 0.4590
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3827 - val_accuracy: 0.8182 - val_loss: 0.4593
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3822 - val_accuracy: 0.8182 - val_loss: 0.4595
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3817 - val_accuracy: 0.8117 - val_loss: 0.4629
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - accuracy: 0.8388 - loss: 0.3818 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8355 - loss: 0.3815 - val_accuracy: 0.8052 - val_loss: 0.4581
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8274 - loss: 0.3814 - val_accuracy: 0.8052 - val_loss: 0.4602
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3809 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3810 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3804 - val_accuracy: 0.8117 - val_loss: 0.4654
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3807 - val_accuracy: 0.8052 - val_loss: 0.4647
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8322 - loss: 0.3799 - val_accuracy: 0.8117 - val_loss: 0.4646
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3794 - val_accuracy: 0.8182 - val_loss: 0.4631
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3795 - val_accuracy: 0.8182 - val_loss: 0.4650
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3795 - val_accuracy: 0.8052 - val_loss: 0.4618
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3784 - val_accuracy: 0.8182 - val_loss: 0.4624
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3780 - val_accuracy: 0.8117 - val_loss: 0.4626
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3781 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8290 - loss: 0.3775 - val_accuracy: 0.8117 - val_loss: 0.4635
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3775 - val_accuracy: 0.8052 - val_loss: 0.4621
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3771 - val_accuracy: 0.8117 - val_loss: 0.4620
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3770 - val_accuracy: 0.8182 - val_loss: 0.4653
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3765 - val_accuracy: 0.8182 - val_loss: 0.4649
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3764 - val_accuracy: 0.8117 - val_loss: 0.4656
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3763 - val_accuracy: 0.8117 - val_loss: 0.4673
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3769 - val_accuracy: 0.8117 - val_loss: 0.4673
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3744 - val_accuracy: 0.8117 - val_loss: 0.4650
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3759 - val_accuracy: 0.8117 - val_loss: 0.4664
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3751 - val_accuracy: 0.8182 - val_loss: 0.4642
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3752 - val_accuracy: 0.8182 - val_loss: 0.4645
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8306 - loss: 0.3746 - val_accuracy: 0.8117 - val_loss: 0.4647
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3730 - val_accuracy: 0.8117 - val_loss: 0.4670
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8339 - loss: 0.3736 - val_accuracy: 0.8117 - val_loss: 0.4675
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3739 - val_accuracy: 0.8117 - val_loss: 0.4686
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3726 - val_accuracy: 0.8182 - val_loss: 0.4666
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8388 - loss: 0.3721 - val_accuracy: 0.8117 - val_loss: 0.4664
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3732 - val_accuracy: 0.8052 - val_loss: 0.4701
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3733 - val_accuracy: 0.8117 - val_loss: 0.4679
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3724 - val_accuracy: 0.8117 - val_loss: 0.4660
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8339 - loss: 0.3719 - val_accuracy: 0.8117 - val_loss: 0.4648
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8306 - loss: 0.3725 - val_accuracy: 0.8117 - val_loss: 0.4645
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8371 - loss: 0.3710 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8322 - loss: 0.3716 - val_accuracy: 0.7987 - val_loss: 0.4668
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8420 - loss: 0.3712 - val_accuracy: 0.8117 - val_loss: 0.4623
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8355 - loss: 0.3708 - val_accuracy: 0.8117 - val_loss: 0.4656

In [254]:
def build_model(hp):
  model = Sequential()
  # model.add(Dense(72, activation='relu', input_dim=8))
  counter =0
  num_layers = hp.Int('num_layers', min_value=1, max_value = 10)
  for i in range(num_layers):
    if counter == 0:
      model.add(Dense(
          hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
          activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid']),
          input_dim=8
      ))

    else:
      model.add(Dense(
          hp.Int('units' + str(i), min_value=8, max_value=128, step=8),
          activation=hp.Choice('activation' + str(i), values=['relu', 'tanh', 'sigmoid'])
      ))
    counter+=1
  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer', values=['rmsprop','adam','sgd', 'nadam','adadelta']),
                loss='binary_crossentropy',
                metrics=['accuracy']
                )
  return model

In [255]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials=3,directory = 'all')

Reloading Tuner from all/untitled_project/tuner0.json

In [256]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units0': 48,
 'activation0': 'tanh',
 'optimizer': 'nadam',
 'units1': 40,
 'activation1': 'tanh',
 'units2': 96,
 'activation2': 'tanh',
 'units3': 120,
 'activation3': 'sigmoid',
 'units4': 120,
 'activation4': 'tanh',
 'units5': 88,
 'activation5': 'sigmoid',
 'units6': 40,
 'activation6': 'tanh'}

In [257]:
tuner.get_best_models()[0].summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'nadam', because it has 2 variables whereas the saved optimizer has 19 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 48)             │           432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 40)             │         1,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 96)             │         3,936 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            97 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,425 (25.10 KB)

 Trainable params: 6,425 (25.10 KB)

 Non-trainable params: 0 (0.00 B)

In [258]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

In [259]:
model = tuner.get_best_models(num_models=1)[0]

In [260]:
model.fit(X_train, y_train, epochs=100, initial_epoch=6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.7459 - loss: 0.4879 - val_accuracy: 0.7922 - val_loss: 0.4573
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.7671 - loss: 0.4712 - val_accuracy: 0.7922 - val_loss: 0.4535
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7736 - loss: 0.4665 - val_accuracy: 0.7792 - val_loss: 0.4528
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7720 - loss: 0.4633 - val_accuracy: 0.8052 - val_loss: 0.4538
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7720 - loss: 0.4625 - val_accuracy: 0.7857 - val_loss: 0.4566
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7687 - loss: 0.4622 - val_accuracy: 0.7727 - val_loss: 0.4599
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4584 - val_accuracy: 0.7727 - val_loss: 0.4651
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4639 - val_accuracy: 0.7857 - val_loss: 0.4557
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4580 - val_accuracy: 0.7727 - val_loss: 0.4544
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4525 - val_accuracy: 0.7727 - val_loss: 0.4581
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4542 - val_accuracy: 0.7792 - val_loss: 0.4618
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4523 - val_accuracy: 0.7792 - val_loss: 0.4600
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4529 - val_accuracy: 0.7792 - val_loss: 0.4593
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4459 - val_accuracy: 0.7792 - val_loss: 0.4578
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4486 - val_accuracy: 0.7792 - val_loss: 0.4584
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4567 - val_accuracy: 0.7857 - val_loss: 0.4539
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4440 - val_accuracy: 0.7857 - val_loss: 0.4566
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4416 - val_accuracy: 0.7857 - val_loss: 0.4557
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4406 - val_accuracy: 0.7727 - val_loss: 0.4595
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4424 - val_accuracy: 0.7727 - val_loss: 0.4554
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4424 - val_accuracy: 0.7597 - val_loss: 0.4696
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4414 - val_accuracy: 0.7792 - val_loss: 0.4576
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4359 - val_accuracy: 0.7662 - val_loss: 0.4592
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4332 - val_accuracy: 0.7922 - val_loss: 0.4556
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4345 - val_accuracy: 0.7597 - val_loss: 0.4707
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4341 - val_accuracy: 0.7922 - val_loss: 0.4570
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4453 - val_accuracy: 0.7922 - val_loss: 0.4565
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4306 - val_accuracy: 0.7792 - val_loss: 0.4602
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4314 - val_accuracy: 0.7792 - val_loss: 0.4631
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4331 - val_accuracy: 0.7792 - val_loss: 0.4578
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4275 - val_accuracy: 0.7792 - val_loss: 0.4595
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4249 - val_accuracy: 0.7662 - val_loss: 0.4754
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4282 - val_accuracy: 0.7727 - val_loss: 0.4688
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4224 - val_accuracy: 0.7987 - val_loss: 0.4615
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7997 - loss: 0.4261 - val_accuracy: 0.7922 - val_loss: 0.4661
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4206 - val_accuracy: 0.7792 - val_loss: 0.4640
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4182 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4173 - val_accuracy: 0.7597 - val_loss: 0.4755
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4189 - val_accuracy: 0.7987 - val_loss: 0.4583
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4167 - val_accuracy: 0.7857 - val_loss: 0.4694
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4133 - val_accuracy: 0.7987 - val_loss: 0.4715
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4156 - val_accuracy: 0.7857 - val_loss: 0.4647
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4127 - val_accuracy: 0.7792 - val_loss: 0.4629
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4109 - val_accuracy: 0.7857 - val_loss: 0.4660
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4114 - val_accuracy: 0.8052 - val_loss: 0.4535
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8029 - loss: 0.4078 - val_accuracy: 0.7792 - val_loss: 0.4720
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4103 - val_accuracy: 0.7987 - val_loss: 0.4772
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.4013 - val_accuracy: 0.7857 - val_loss: 0.4618
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4116 - val_accuracy: 0.7857 - val_loss: 0.4643
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4024 - val_accuracy: 0.7857 - val_loss: 0.4697
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4021 - val_accuracy: 0.8052 - val_loss: 0.4651
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4015 - val_accuracy: 0.7792 - val_loss: 0.4700
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8029 - loss: 0.4065 - val_accuracy: 0.8117 - val_loss: 0.4610
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8176 - loss: 0.3961 - val_accuracy: 0.7922 - val_loss: 0.4683
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3978 - val_accuracy: 0.7922 - val_loss: 0.4684
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8143 - loss: 0.3972 - val_accuracy: 0.7987 - val_loss: 0.4632
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8111 - loss: 0.3948 - val_accuracy: 0.8182 - val_loss: 0.4608
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4052 - val_accuracy: 0.7922 - val_loss: 0.4691
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3894 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3941 - val_accuracy: 0.8117 - val_loss: 0.4614
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.3895 - val_accuracy: 0.8117 - val_loss: 0.4650
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3863 - val_accuracy: 0.8052 - val_loss: 0.4631
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3845 - val_accuracy: 0.8052 - val_loss: 0.4655
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.3854 - val_accuracy: 0.8117 - val_loss: 0.4718
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3866 - val_accuracy: 0.7922 - val_loss: 0.4669
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3829 - val_accuracy: 0.7987 - val_loss: 0.4691
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3908 - val_accuracy: 0.8052 - val_loss: 0.4649
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3801 - val_accuracy: 0.7857 - val_loss: 0.4600
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8290 - loss: 0.3731 - val_accuracy: 0.7857 - val_loss: 0.4673
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3886 - val_accuracy: 0.7922 - val_loss: 0.4726
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8322 - loss: 0.3738 - val_accuracy: 0.8117 - val_loss: 0.4675
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.3779 - val_accuracy: 0.8117 - val_loss: 0.4598
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8274 - loss: 0.3712 - val_accuracy: 0.8117 - val_loss: 0.4625
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8290 - loss: 0.3714 - val_accuracy: 0.7987 - val_loss: 0.4713
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8371 - loss: 0.3687 - val_accuracy: 0.7987 - val_loss: 0.4659
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8225 - loss: 0.3645 - val_accuracy: 0.8117 - val_loss: 0.4653
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8274 - loss: 0.3679 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8306 - loss: 0.3696 - val_accuracy: 0.7792 - val_loss: 0.4622
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8290 - loss: 0.3678 - val_accuracy: 0.8117 - val_loss: 0.4536
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8322 - loss: 0.3649 - val_accuracy: 0.8117 - val_loss: 0.4683
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8388 - loss: 0.3598 - val_accuracy: 0.7792 - val_loss: 0.4646
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8371 - loss: 0.3608 - val_accuracy: 0.8052 - val_loss: 0.4661
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3552 - val_accuracy: 0.7987 - val_loss: 0.4552
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3501 - val_accuracy: 0.7922 - val_loss: 0.4550
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8420 - loss: 0.3507 - val_accuracy: 0.8052 - val_loss: 0.4656
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3476 - val_accuracy: 0.7987 - val_loss: 0.4667
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8306 - loss: 0.3499 - val_accuracy: 0.7922 - val_loss: 0.4545
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8404 - loss: 0.3485 - val_accuracy: 0.7922 - val_loss: 0.4720
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3462 - val_accuracy: 0.7922 - val_loss: 0.4598
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3511 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3380 - val_accuracy: 0.7857 - val_loss: 0.4649
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8550 - loss: 0.3364 - val_accuracy: 0.8052 - val_loss: 0.4583
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8469 - loss: 0.3351 - val_accuracy: 0.7857 - val_loss: 0.4638
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8518 - loss: 0.3323 - val_accuracy: 0.7857 - val_loss: 0.4772